apiVersion: apps/v1
kind: Deployment
metadata:
  name: ullis-jenkins-deployment
  labels:
    app: jenkins          # used by the service selector
  namespace: ullisjenkinsspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:             # configuration, of a pod
      labels:
        app: jenkins        # used by the servoce selector
    spec:                 # blueprint for a pod
      containers:
      - name: jenkins
        image: REPLACE_ME     # das wird im Jenkinsfile durch den azure-namen ersetzt
        ports:
        - containerPort: 80   # should match targetPort in Service
