apiVersion: v1                # service provides studry ip-adress for pod
kind: Service                 # do i need an extra service for every pod?
metadata:
  name: ullis-jenkins-service
  namespace: ullisjenkinsspace       
spec:
  selector:
    app: jenkins                  # selects label of the deployment and the pods in it
  ports:
    - port: 80                  # an diesem Port hört der Service. wird con ingress angesteuert                          # hier ggf. targetPort, wenn anders als Port
                                # targetPort matches containerPort in deployment (pods)
  type: LoadBalancer